settings:
  docker:
    build_context_root: ../
    dockerignore: ../.dockerignore
    requirements:
      # - scikit-surprise
steps:
  load_data:
    enable_cache: False
    experiment_tracker: mlflow_experiment_tracker
    parameters:
      test_size: 0.25
  train:
    enable_cache: False
  evaluate:
    enable_cache: False
    experiment_tracker: mlflow_experiment_tracker
