settings:
  docker:
    dockerignore: .dockerignore
steps:
  download_dataset:
    enable_cache: False
    parameters:
      # Path to directory where dataset will be downloaded
      data_dir: "data/"
  convert_to_hg_dataset:
    enable_cache: False
