name: CI

on:
  workflow_call:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci-tests:
    name: Pytest CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
    timeout-minutes: 15

    # disable zenml analytics logging for ci
    env:
      ZENML_ANALYTICS_OPT_IN: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load cached venv
        id: python_cache
        uses: actions/cache@v3
        with:
          path: venv
          key: pip-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('recommendation/requirements.txt') }}

      # Install dependencies if cache does not exist
      - name: Install dependencies
        if: steps.python_cache.outputs.cache-hit != 'true'
        run: |
          if [ -d "venv" ]; then rm -rf venv; fi

          python3 -m venv venv 

          venv/bin/python3 -m pip install -r recommendation/requirements.txt

      - name: Run tests with pytest
        run: |
          source venv/bin/activate
          
          python -m pytest recommendation/tests/